- name: DB smoke test
  env:
    DB_HOST: ${{ secrets.DB_HOST }}
    DB_PORT: ${{ secrets.DB_PORT }}
    DB_NAME: ${{ secrets.DB_NAME }}
    DB_USER: ${{ secrets.DB_USER }}
    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  run: |
    python - <<'PY'
    import os, psycopg2, sys
    try:
        conn = psycopg2.connect(
            host=os.environ["DB_HOST"],
            port=os.environ["DB_PORT"],
            dbname=os.environ["DB_NAME"],
            user=os.environ["DB_USER"],
            password=os.environ["DB_PASSWORD"],
            sslmode="require",
        )
        with conn, conn.cursor() as cur:
            cur.execute("select 1")
            assert cur.fetchone()[0] == 1
        print("✅ Secrets OK: DB connection succeeded.")
    except Exception as e:
        print("❌ Secrets/DB check failed:", e)
        sys.exit(1)
    PY
