name: ETL

on:
  schedule: [{ cron: "0 1 * * *" }]   # every day 01:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    # Make DB secrets available to ALL steps
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"        # 3.11 also fine

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate signals
        run: python jobs/make_signals.py

      - name: Execute orders (paper)
        run: python services/executor.py

      - name: Update daily PnL
        run: python etl/push_daily_pnl.py
