# .github/workflows/etl.yml
name: ETL

on:
  schedule:
    - cron: "0 1 * * *"     # every day 01:00 UTC
  workflow_dispatch: {}     # allow manual runs

jobs:
  db_smoke:
    name: DB smoke test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install DB client
        run: pip install psycopg2-binary
      - name: Check secrets + DB
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          python - <<'PY'
          import os,sys,psycopg2
          try:
              conn = psycopg2.connect(
                  host=os.environ["DB_HOST"], port=os.environ["DB_PORT"],
                  dbname=os.environ["DB_NAME"], user=os.environ["DB_USER"],
                  password=os.environ["DB_PASSWORD"], sslmode="require")
              with conn, conn.cursor() as cur:
                  cur.execute("select 1"); assert cur.fetchone()[0]==1
              print("✅ Secrets/DB OK")
          except Exception as e:
              print("❌ Secrets/DB check failed:", e); sys.exit(1)
          PY

  run_etl:
    name: Run ETL
    needs: db_smoke
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt yfinance
      - name: Execute ETL
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: python etl/push_daily_pnl.py
