[db]
host = "ep-raspy-smoke-ae8epwey-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"      # e.g. ep-red-123.eu-central-1.aws.neon.tech
port = "5432"
dbname = "neondb"
user = "neondb_owner"
password = "npg_XasVR6uImqh0"
